// Map a skill string -> { url, label } pointing to a free learning resource.
// Preference order: W3Schools (beginner-friendly) > MDN (web standards) > official
// vendor docs/tutorials > freeCodeCamp / Coursera / YouTube > a Google search fallback.
// Goal: every common skill resolves to a real platform; Google is reserved for truly
// obscure entries.
// Canonicalization mirrors apps/api/app/services/skills.py so a backend skill that
// matched a canonical form also resolves here.

const DIRECT = {
  // ---------- Web fundamentals ----------
  html: "https://www.w3schools.com/html/",
  css: "https://www.w3schools.com/css/",
  javascript: "https://www.w3schools.com/js/",
  typescript: "https://www.typescriptlang.org/docs/handbook/intro.html",
  jquery: "https://www.w3schools.com/jquery/",
  bootstrap: "https://www.w3schools.com/bootstrap5/",
  tailwindcss: "https://tailwindcss.com/docs/installation",
  sass: "https://sass-lang.com/guide/",
  less: "https://lesscss.org/usage/",
  materialui: "https://mui.com/material-ui/getting-started/",
  chakraui: "https://chakra-ui.com/getting-started",
  shadcnui: "https://ui.shadcn.com/docs",
  webpack: "https://webpack.js.org/concepts/",
  vite: "https://vitejs.dev/guide/",
  parcel: "https://parceljs.org/docs/",
  babel: "https://babeljs.io/docs/",
  eslint: "https://eslint.org/docs/latest/use/getting-started",
  prettier: "https://prettier.io/docs/en/install",
  storybook: "https://storybook.js.org/tutorials/",
  threejs: "https://threejs.org/manual/",
  d3js: "https://d3js.org/getting-started",
  // ---------- Programming languages ----------
  python: "https://www.w3schools.com/python/",
  java: "https://www.w3schools.com/java/",
  csharp: "https://www.w3schools.com/cs/",
  cplusplus: "https://www.w3schools.com/cpp/",
  c: "https://www.w3schools.com/c/",
  php: "https://www.w3schools.com/php/",
  ruby: "https://www.ruby-lang.org/en/documentation/quickstart/",
  golang: "https://go.dev/learn/",
  rust: "https://doc.rust-lang.org/book/",
  kotlin: "https://kotlinlang.org/docs/getting-started.html",
  swift: "https://www.swift.org/getting-started/",
  scala: "https://docs.scala-lang.org/tour/tour-of-scala.html",
  dart: "https://dart.dev/guides",
  r: "https://www.w3schools.com/r/",
  perl: "https://www.perl.org/learn.html",
  lua: "https://www.lua.org/pil/contents.html",
  matlab: "https://matlabacademy.mathworks.com/details/matlab-onramp/gettingstarted",
  vba: "https://learn.microsoft.com/en-us/office/vba/api/overview/",
  groovy: "https://groovy-lang.org/learn.html",
  haskell: "https://www.haskell.org/documentation/",
  elixir: "https://elixir-lang.org/getting-started/introduction.html",
  erlang: "https://www.erlang.org/docs",
  clojure: "https://clojure.org/guides/getting_started",
  solidity: "https://docs.soliditylang.org/en/latest/",
  assembly: "https://www.tutorialspoint.com/assembly_programming/index.htm",
  fsharp: "https://learn.microsoft.com/en-us/dotnet/fsharp/",
  // ---------- Web frameworks / libraries ----------
  reactjs: "https://react.dev/learn",
  reactnative: "https://reactnative.dev/docs/tutorial",
  redux: "https://redux.js.org/tutorials/essentials/part-1-overview-concepts",
  reactquery: "https://tanstack.com/query/latest/docs/framework/react/quick-start",
  nextjs: "https://nextjs.org/learn",
  remix: "https://remix.run/docs/en/main/start/tutorial",
  gatsby: "https://www.gatsbyjs.com/docs/tutorial/",
  vuejs: "https://vuejs.org/tutorial/",
  nuxtjs: "https://nuxt.com/docs/getting-started/introduction",
  angular: "https://angular.dev/tutorials",
  angularjs: "https://docs.angularjs.org/tutorial",
  svelte: "https://learn.svelte.dev/",
  sveltekit: "https://learn.svelte.dev/tutorial/welcome-to-svelte",
  emberjs: "https://guides.emberjs.com/release/tutorial/part-1/",
  backbonejs: "https://backbonejs.org/",
  alpinejs: "https://alpinejs.dev/start-here",
  htmx: "https://htmx.org/docs/",
  // ---------- Backend frameworks ----------
  nodejs: "https://nodejs.org/en/learn/getting-started/introduction-to-nodejs",
  expressjs: "https://expressjs.com/en/starter/installing.html",
  nestjs: "https://docs.nestjs.com/first-steps",
  koajs: "https://koajs.com/",
  fastify: "https://fastify.dev/docs/latest/Guides/Getting-Started/",
  spring: "https://spring.io/guides/gs/spring-boot",
  springboot: "https://spring.io/guides/gs/spring-boot",
  django: "https://docs.djangoproject.com/en/stable/intro/tutorial01/",
  flask: "https://flask.palletsprojects.com/en/latest/tutorial/",
  fastapi: "https://fastapi.tiangolo.com/tutorial/",
  laravel: "https://laravel.com/docs",
  symfony: "https://symfony.com/doc/current/the-fast-track/en/index.html",
  codeigniter: "https://codeigniter.com/user_guide/tutorial/",
  cakephp: "https://book.cakephp.org/4/en/quickstart.html",
  rails: "https://guides.rubyonrails.org/",
  aspnet: "https://learn.microsoft.com/en-us/aspnet/core/tutorials/",
  dotnetcore: "https://learn.microsoft.com/en-us/dotnet/core/tutorials/",
  phoenix: "https://hexdocs.pm/phoenix/up_and_running.html",
  gin: "https://gin-gonic.com/docs/quickstart/",
  echo: "https://echo.labstack.com/docs/quick-start",
  fiber: "https://docs.gofiber.io/",
  // ---------- Mobile ----------
  android: "https://developer.android.com/courses",
  ios: "https://developer.apple.com/tutorials/swiftui",
  swiftui: "https://developer.apple.com/tutorials/swiftui",
  jetpackcompose: "https://developer.android.com/develop/ui/compose/tutorial",
  flutter: "https://docs.flutter.dev/get-started/codelab",
  ionic: "https://ionicframework.com/docs/intro/cli",
  xamarin: "https://learn.microsoft.com/en-us/xamarin/get-started/",
  cordova: "https://cordova.apache.org/docs/en/latest/guide/overview/",
  capacitor: "https://capacitorjs.com/docs/getting-started",
  nativescript: "https://docs.nativescript.org/",
  // ---------- Databases ----------
  sql: "https://www.w3schools.com/sql/",
  mysql: "https://www.w3schools.com/mysql/",
  postgresql: "https://www.postgresqltutorial.com/",
  sqlite: "https://www.sqlitetutorial.net/",
  mongodb: "https://learn.mongodb.com/",
  redis: "https://redis.io/docs/latest/develop/",
  cassandra: "https://cassandra.apache.org/doc/latest/cassandra/getting_started/",
  dynamodb: "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html",
  firestore: "https://firebase.google.com/docs/firestore/quickstart",
  oracle: "https://docs.oracle.com/en/database/oracle/oracle-database/",
  sqlserver: "https://learn.microsoft.com/en-us/sql/sql-server/tutorials-for-sql-server",
  mariadb: "https://mariadb.com/kb/en/documentation/",
  neo4j: "https://neo4j.com/docs/getting-started/",
  couchdb: "https://docs.couchdb.org/en/stable/intro/index.html",
  influxdb: "https://docs.influxdata.com/influxdb/v2/get-started/",
  graphql: "https://graphql.org/learn/",
  firebase: "https://firebase.google.com/docs",
  supabase: "https://supabase.com/docs/guides/getting-started",
  prisma: "https://www.prisma.io/docs/getting-started",
  sequelize: "https://sequelize.org/docs/v6/getting-started/",
  sqlalchemy: "https://docs.sqlalchemy.org/en/20/tutorial/",
  // ---------- DevOps / cloud ----------
  docker: "https://docs.docker.com/get-started/",
  dockercompose: "https://docs.docker.com/compose/gettingstarted/",
  kubernetes: "https://kubernetes.io/docs/tutorials/",
  helm: "https://helm.sh/docs/intro/quickstart/",
  argocd: "https://argo-cd.readthedocs.io/en/stable/getting_started/",
  terraform: "https://developer.hashicorp.com/terraform/tutorials",
  ansible: "https://docs.ansible.com/ansible/latest/getting_started/index.html",
  puppet: "https://www.puppet.com/docs/puppet/8/quick_start.html",
  chef: "https://docs.chef.io/learn/",
  vagrant: "https://developer.hashicorp.com/vagrant/tutorials",
  aws: "https://aws.amazon.com/getting-started/",
  googlecloud: "https://cloud.google.com/training",
  azure: "https://learn.microsoft.com/en-us/training/azure/",
  heroku: "https://devcenter.heroku.com/start",
  digitalocean: "https://www.digitalocean.com/community/tutorials",
  vercel: "https://vercel.com/docs/getting-started-with-vercel",
  netlify: "https://docs.netlify.com/welcome/add-new-site/",
  cloudflare: "https://developers.cloudflare.com/learning-paths/",
  linux: "https://www.w3schools.com/linux/",
  ubuntu: "https://ubuntu.com/tutorials",
  bash: "https://www.w3schools.com/bash/",
  shell: "https://www.w3schools.com/bash/",
  powershell: "https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/00-introduction",
  nginx: "https://nginx.org/en/docs/",
  apache: "https://httpd.apache.org/docs/current/",
  jenkins: "https://www.jenkins.io/doc/tutorials/",
  githubactions: "https://docs.github.com/en/actions",
  gitlabci: "https://docs.gitlab.com/ee/ci/quick_start/",
  circleci: "https://circleci.com/docs/getting-started/",
  travisci: "https://docs.travis-ci.com/user/tutorial/",
  cicd: "https://docs.github.com/en/actions",
  git: "https://www.w3schools.com/git/",
  github: "https://www.w3schools.com/git/",
  gitlab: "https://docs.gitlab.com/ee/tutorials/",
  bitbucket: "https://support.atlassian.com/bitbucket-cloud/resources/",
  // ---------- Monitoring / observability ----------
  prometheus: "https://prometheus.io/docs/tutorials/getting_started/",
  grafana: "https://grafana.com/tutorials/",
  datadog: "https://docs.datadoghq.com/getting_started/",
  splunk: "https://docs.splunk.com/Documentation/Splunk/latest/SearchTutorial/WelcometotheSearchTutorial",
  elk: "https://www.elastic.co/guide/en/elastic-stack/current/learning-center.html",
  logstash: "https://www.elastic.co/guide/en/logstash/current/getting-started-with-logstash.html",
  kibana: "https://www.elastic.co/guide/en/kibana/current/get-started.html",
  newrelic: "https://docs.newrelic.com/docs/new-relic-solutions/get-started/quick-launch-guide/",
  sentry: "https://docs.sentry.io/",
  // ---------- Testing ----------
  jest: "https://jestjs.io/docs/getting-started",
  vitest: "https://vitest.dev/guide/",
  mocha: "https://mochajs.org/#getting-started",
  chai: "https://www.chaijs.com/guide/",
  pytest: "https://docs.pytest.org/en/stable/getting-started.html",
  cypress: "https://docs.cypress.io",
  playwright: "https://playwright.dev/docs/intro",
  selenium: "https://www.selenium.dev/documentation/",
  puppeteer: "https://pptr.dev/",
  appium: "https://appium.io/docs/en/latest/quickstart/",
  junit: "https://junit.org/junit5/docs/current/user-guide/",
  nunit: "https://docs.nunit.org/articles/nunit/getting-started/installation.html",
  testng: "https://testng.org/doc/documentation-main.html",
  rspec: "https://rspec.info/documentation/",
  // ---------- AI / ML / data science ----------
  machinelearning: "https://www.coursera.org/learn/machine-learning",
  artificialintelligence: "https://www.coursera.org/learn/ai-for-everyone",
  deeplearning: "https://www.deeplearning.ai/courses/",
  tensorflow: "https://www.tensorflow.org/tutorials",
  pytorch: "https://pytorch.org/tutorials/",
  keras: "https://keras.io/getting_started/",
  pandas: "https://pandas.pydata.org/docs/getting_started/index.html",
  numpy: "https://numpy.org/learn/",
  scikitlearn: "https://scikit-learn.org/stable/tutorial/index.html",
  matplotlib: "https://matplotlib.org/stable/users/getting_started/",
  seaborn: "https://seaborn.pydata.org/tutorial.html",
  plotly: "https://plotly.com/python/getting-started/",
  jupyter: "https://docs.jupyter.org/en/latest/start/index.html",
  anaconda: "https://docs.anaconda.com/anaconda/user-guide/getting-started/",
  opencv: "https://docs.opencv.org/4.x/d9/df8/tutorial_root.html",
  nltk: "https://www.nltk.org/book/",
  spacy: "https://spacy.io/usage/spacy-101",
  huggingface: "https://huggingface.co/learn",
  langchain: "https://python.langchain.com/docs/get_started/introduction",
  llamaindex: "https://docs.llamaindex.ai/en/stable/getting_started/starter_example/",
  openaiapi: "https://platform.openai.com/docs/quickstart",
  anthropicapi: "https://docs.anthropic.com/en/docs/get-started",
  mlflow: "https://mlflow.org/docs/latest/getting-started/index.html",
  nlp: "https://www.coursera.org/specializations/natural-language-processing",
  computervision: "https://www.coursera.org/specializations/deep-learning",
  datascience: "https://www.coursera.org/professional-certificates/ibm-data-science",
  dataanalyst: "https://www.coursera.org/professional-certificates/google-data-analytics",
  // ---------- Data engineering / big data ----------
  apachespark: "https://spark.apache.org/docs/latest/quick-start.html",
  hadoop: "https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/SingleCluster.html",
  hive: "https://cwiki.apache.org/confluence/display/Hive/Tutorial",
  airflow: "https://airflow.apache.org/docs/apache-airflow/stable/tutorial/index.html",
  dbt: "https://docs.getdbt.com/guides",
  snowflake: "https://docs.snowflake.com/en/learn-tutorials",
  databricks: "https://docs.databricks.com/en/getting-started/index.html",
  bigquery: "https://cloud.google.com/bigquery/docs/tutorials",
  redshift: "https://docs.aws.amazon.com/redshift/latest/gsg/getting-started.html",
  // ---------- BI / analytics ----------
  tableau: "https://www.tableau.com/learn/training",
  powerbi: "https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started",
  looker: "https://cloud.google.com/looker/docs/intro",
  googleanalytics: "https://skillshop.exceedlms.com/student/catalog/list?category_ids=53-google-analytics",
  excel: "https://support.microsoft.com/en-us/office/excel-video-training-9bc05390-e94c-46af-a5b3-d7c22f6990bb",
  googlesheets: "https://support.google.com/a/users/answer/9282959",
  // ---------- Cybersecurity ----------
  cybersecurity: "https://www.coursera.org/specializations/cyber-security",
  webapplicationsecurity: "https://portswigger.net/web-security",
  apipenetrationtesting: "https://owasp.org/www-project-api-security/",
  mobileapplicationsecurity: "https://owasp.org/www-project-mobile-app-security/",
  aillmpenetrationtesting: "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
  thickclientpenetrationtesting: "https://book.hacktricks.xyz/network-services-pentesting/pentesting-thick-clients",
  externalnetworksecurity: "https://www.hackerone.com/knowledge-center/network-penetration-testing",
  owasptop10: "https://owasp.org/www-project-top-ten/",
  owasptop10andbusinesslogic: "https://owasp.org/www-project-top-ten/",
  burpsuite: "https://portswigger.net/web-security",
  owaspzap: "https://www.zaproxy.org/getting-started/",
  nmap: "https://nmap.org/book/",
  wireshark: "https://www.wireshark.org/docs/wsug_html_chunked/",
  metasploit: "https://www.offsec.com/metasploit-unleashed/",
  sqlmap: "https://github.com/sqlmapproject/sqlmap/wiki/Usage",
  nuclei: "https://docs.projectdiscovery.io/tools/nuclei/overview",
  frida: "https://frida.re/docs/home/",
  nessus: "https://docs.tenable.com/nessus.htm",
  nexpose: "https://docs.rapid7.com/nexpose/",
  kalilinux: "https://www.kali.org/docs/",
  cryptography: "https://www.coursera.org/learn/crypto",
  ethicalhacking: "https://www.cybrary.it/catalog/ethical-hacking/",
  // ---------- APIs / protocols ----------
  restapi: "https://www.freecodecamp.org/news/rest-api-tutorial-rest-client-rest-service-and-api-calls-explained-with-code-examples/",
  rest: "https://www.freecodecamp.org/news/rest-api-tutorial-rest-client-rest-service-and-api-calls-explained-with-code-examples/",
  soap: "https://www.w3schools.com/xml/xml_soap.asp",
  grpc: "https://grpc.io/docs/what-is-grpc/introduction/",
  websockets: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
  oauth: "https://www.oauth.com/",
  jwt: "https://jwt.io/introduction",
  openapi: "https://learn.openapis.org/",
  swagger: "https://swagger.io/docs/specification/about/",
  postman: "https://learning.postman.com/docs/introduction/overview/",
  insomnia: "https://docs.insomnia.rest/",
  // ---------- Messaging / streams ----------
  rabbitmq: "https://www.rabbitmq.com/getstarted.html",
  kafka: "https://kafka.apache.org/quickstart",
  activemq: "https://activemq.apache.org/getting-started",
  // ---------- Search ----------
  elasticsearch: "https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html",
  algolia: "https://www.algolia.com/doc/guides/getting-started/what-is-algolia/",
  // ---------- Design tools ----------
  figma: "https://help.figma.com/hc/en-us/categories/360002042553-Get-started",
  adobexd: "https://helpx.adobe.com/xd/get-started.html",
  sketch: "https://www.sketch.com/docs/",
  photoshop: "https://helpx.adobe.com/photoshop/tutorials.html",
  illustrator: "https://helpx.adobe.com/illustrator/tutorials.html",
  indesign: "https://helpx.adobe.com/indesign/tutorials.html",
  aftereffects: "https://helpx.adobe.com/after-effects/tutorials.html",
  premierepro: "https://helpx.adobe.com/premiere-pro/tutorials.html",
  canva: "https://www.canva.com/designschool/",
  invision: "https://support.invisionapp.com/hc/en-us/categories/360000018263-Learn-InVision",
  // ---------- Project / collaboration ----------
  jira: "https://www.atlassian.com/agile/tutorials",
  confluence: "https://www.atlassian.com/software/confluence/guides",
  trello: "https://trello.com/guide",
  asana: "https://academy.asana.com/",
  clickup: "https://university.clickup.com/",
  monday: "https://monday.com/helpcenter/learning/learning-center",
  notion: "https://www.notion.so/help/guides",
  slack: "https://slack.com/help/categories/360000049063",
  microsoftteams: "https://support.microsoft.com/en-us/teams",
  // ---------- CMS / e-commerce ----------
  wordpress: "https://learn.wordpress.org/",
  shopify: "https://help.shopify.com/en/manual/intro-to-shopify",
  magento: "https://developer.adobe.com/commerce/docs/",
  woocommerce: "https://woocommerce.com/documentation/woocommerce/getting-started/",
  drupal: "https://www.drupal.org/docs/getting-started",
  joomla: "https://docs.joomla.org/Beginners",
  wix: "https://support.wix.com/en/getting-started",
  webflow: "https://university.webflow.com/",
  squarespace: "https://support.squarespace.com/hc/en-us/categories/206542167-Getting-started",
  // ---------- Marketing / SEO ----------
  seo: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide",
  googleads: "https://skillshop.exceedlms.com/student/catalog/list?category_ids=2844-google-ads",
  facebookads: "https://www.facebook.com/business/learn",
  metaads: "https://www.facebook.com/business/learn",
  hubspot: "https://academy.hubspot.com/",
  mailchimp: "https://mailchimp.com/help/getting-started/",
  semrush: "https://www.semrush.com/academy/",
  ahrefs: "https://ahrefs.com/academy",
  contentmarketing: "https://academy.hubspot.com/courses/content-marketing",
  emailmarketing: "https://mailchimp.com/resources/email-marketing-guide/",
  // ---------- CRM / ERP ----------
  salesforce: "https://trailhead.salesforce.com/",
  sap: "https://learning.sap.com/",
  oracleerp: "https://docs.oracle.com/en/cloud/saas/applications.html",
  netsuite: "https://docs.oracle.com/en/cloud/saas/netsuite/",
  zoho: "https://www.zoho.com/academy/",
  microsoftdynamics: "https://learn.microsoft.com/en-us/dynamics365/",
  // ---------- Office / productivity ----------
  msoffice: "https://support.microsoft.com/en-us/office",
  word: "https://support.microsoft.com/en-us/word",
  powerpoint: "https://support.microsoft.com/en-us/powerpoint",
  outlook: "https://support.microsoft.com/en-us/outlook",
  googleworkspace: "https://support.google.com/a/users",
  // ---------- Methodologies ----------
  agile: "https://www.atlassian.com/agile",
  scrum: "https://www.scrum.org/resources/what-scrum-module",
  kanban: "https://www.atlassian.com/agile/kanban",
  waterfall: "https://www.coursera.org/articles/waterfall-methodology",
  lean: "https://www.lean.org/lexicon-terms/",
  safe: "https://scaledagileframework.com/",
  // ---------- CS concepts ----------
  oop: "https://www.freecodecamp.org/news/object-oriented-programming-concepts-21bb035f7260/",
  functionalprogramming: "https://www.freecodecamp.org/news/an-introduction-to-the-basic-principles-of-functional-programming-a2c2a15c84/",
  designpatterns: "https://refactoring.guru/design-patterns",
  datastructures: "https://www.geeksforgeeks.org/data-structures/",
  algorithms: "https://www.geeksforgeeks.org/fundamentals-of-algorithms/",
  microservices: "https://microservices.io/patterns/microservices.html",
  systemdesign: "https://github.com/donnemartin/system-design-primer",
  tdd: "https://www.agilealliance.org/glossary/tdd/",
  bdd: "https://cucumber.io/docs/bdd/",
  ddd: "https://martinfowler.com/bliki/DomainDrivenDesign.html",
  cleancode: "https://github.com/ryanmcdermott/clean-code-javascript",
  solid: "https://www.freecodecamp.org/news/solid-the-first-5-principles-of-object-oriented-design-a-with-javascript-7c1ad24a8fab/",
  mvc: "https://developer.mozilla.org/en-US/docs/Glossary/MVC",
  serverless: "https://aws.amazon.com/serverless/learn/",
  // ---------- Blockchain ----------
  blockchain: "https://ethereum.org/en/developers/tutorials/",
  ethereum: "https://ethereum.org/en/developers/tutorials/",
  web3: "https://ethereum.org/en/developers/docs/web2-vs-web3/",
  hardhat: "https://hardhat.org/tutorial",
  truffle: "https://archive.trufflesuite.com/docs/truffle/quickstart/",
  smartcontracts: "https://docs.soliditylang.org/en/latest/introduction-to-smart-contracts.html",
  // ---------- Game dev ----------
  unity: "https://learn.unity.com/",
  unrealengine: "https://dev.epicgames.com/community/learning",
  godot: "https://docs.godotengine.org/en/stable/getting_started/introduction/",
  // ---------- Hardware / embedded ----------
  arduino: "https://docs.arduino.cc/learn/",
  raspberrypi: "https://projects.raspberrypi.org/en/",
  iot: "https://www.coursera.org/specializations/iot",
  // ---------- Networking ----------
  networking: "https://www.cisco.com/c/en/us/training-events/training-certifications/training/training-services/courses/network-fundamentals.html",
  tcpip: "https://www.tutorialspoint.com/data_communication_computer_network/tcp_ip_model.htm",
  dns: "https://www.cloudflare.com/learning/dns/what-is-dns/",
  http: "https://developer.mozilla.org/en-US/docs/Web/HTTP",
  // ---------- .NET / Microsoft stack ----------
  dotnet: "https://learn.microsoft.com/en-us/dotnet/",
  entityframework: "https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app",
  blazor: "https://learn.microsoft.com/en-us/aspnet/core/blazor/",
  // ---------- Career tracks (kept for users who type a track name) ----------
  frontend: "https://www.theodinproject.com/paths/foundations/courses/foundations",
  backend: "https://roadmap.sh/backend",
  fullstack: "https://www.theodinproject.com/paths/full-stack-javascript",
  devops: "https://www.coursera.org/specializations/devops-on-aws",
  ux: "https://www.coursera.org/professional-certificates/google-ux-design",
  uxdesign: "https://www.coursera.org/professional-certificates/google-ux-design",
  uidesign: "https://www.coursera.org/professional-certificates/google-ux-design",
  qa: "https://www.coursera.org/learn/introduction-software-testing",
  gamedeveloper: "https://learn.unity.com/",
  productmanager: "https://www.coursera.org/professional-certificates/google-project-management",
  projectmanagement: "https://www.coursera.org/professional-certificates/google-project-management",
  technicalwriter: "https://developers.google.com/tech-writing",
};

function canonicalKey(skill) {
  const s = String(skill || "").trim().toLowerCase();
  // Strip whitespace, hyphens, underscores, dots, slashes (matches services/skills.py).
  const stripped = s.replace(/[\s\-_./]+/g, "");
  // A small alias layer for the most common variants — keep it in sync with the
  // backend canonicalizer's intent.
  const ALIASES = {
    // Language shortcuts
    js: "javascript",
    ts: "typescript",
    py: "python",
    "c++": "cplusplus",
    "c#": "csharp",
    "f#": "fsharp",
    ".net": "dotnet",
    dotnetcore: "dotnet",
    aspdotnet: "aspnet",
    aspnetcore: "aspnet",
    // DB variants
    postgres: "postgresql",
    mssql: "sqlserver",
    microsoftsqlserver: "sqlserver",
    msaccess: "sql",
    // Cloud variants
    amazonwebservices: "aws",
    gcp: "googlecloud",
    googlecloudplatform: "googlecloud",
    microsoftazure: "azure",
    // Container/k8s
    k8s: "kubernetes",
    kube: "kubernetes",
    // JS frameworks
    react: "reactjs",
    "react.js": "reactjs",
    reactrouter: "reactjs",
    "node.js": "nodejs",
    "next.js": "nextjs",
    "nuxt.js": "nuxtjs",
    "vue.js": "vuejs",
    vue: "vuejs",
    "express.js": "expressjs",
    express: "expressjs",
    "nest.js": "nestjs",
    nest: "nestjs",
    // Mobile
    androiddevelopment: "android",
    androidstudio: "android",
    iosdevelopment: "ios",
    // AI/ML
    ml: "machinelearning",
    ai: "artificialintelligence",
    genai: "artificialintelligence",
    generativeai: "artificialintelligence",
    sklearn: "scikitlearn",
    cv: "computervision",
    // Data
    spark: "apachespark",
    apacheairflow: "airflow",
    apachekafka: "kafka",
    // BI
    msexcel: "excel",
    microsoftexcel: "excel",
    mspowerbi: "powerbi",
    msword: "word",
    mspowerpoint: "powerpoint",
    msoutlook: "outlook",
    msteams: "microsoftteams",
    teams: "microsoftteams",
    office365: "msoffice",
    microsoftoffice: "msoffice",
    google: "googleworkspace",
    gsuite: "googleworkspace",
    googledocs: "googleworkspace",
    // Design
    adobephotoshop: "photoshop",
    adobeillustrator: "illustrator",
    adobeindesign: "indesign",
    adobexd: "adobexd",
    adobeaftereffects: "aftereffects",
    adobepremiere: "premierepro",
    adobepremierepro: "premierepro",
    creativesuite: "photoshop",
    adobecreativesuite: "photoshop",
    // Marketing
    googleanalytics4: "googleanalytics",
    ga: "googleanalytics",
    ga4: "googleanalytics",
    googleadwords: "googleads",
    adwords: "googleads",
    facebookadsmanager: "facebookads",
    metabusinesssuite: "facebookads",
    metaadsmanager: "facebookads",
    socialmediamarketing: "facebookads",
    digitalmarketing: "googleads",
    searchengineoptimization: "seo",
    // APIs
    restapis: "restapi",
    restfulapi: "restapi",
    restfulapis: "restapi",
    restfulservices: "restapi",
    webservices: "restapi",
    apidesign: "restapi",
    apidevelopment: "restapi",
    apiintegration: "restapi",
    soapapi: "soap",
    websocket: "websockets",
    jsonwebtoken: "jwt",
    openapispec: "openapi",
    openapispecification: "openapi",
    // Security skill variants
    apipentesting: "apipenetrationtesting",
    apipentest: "apipenetrationtesting",
    apisecurity: "apipenetrationtesting",
    mobilepentesting: "mobileapplicationsecurity",
    mobilesecurity: "mobileapplicationsecurity",
    llmsecurity: "aillmpenetrationtesting",
    llmpentesting: "aillmpenetrationtesting",
    aisecurity: "aillmpenetrationtesting",
    thickclientpentesting: "thickclientpenetrationtesting",
    webappsecurity: "webapplicationsecurity",
    websecurity: "webapplicationsecurity",
    networksecurity: "externalnetworksecurity",
    networkpentesting: "externalnetworksecurity",
    pentesting: "webapplicationsecurity",
    penetrationtesting: "webapplicationsecurity",
    informationsecurity: "cybersecurity",
    infosec: "cybersecurity",
    zap: "owaspzap",
    owaspzapproxy: "owaspzap",
    zedattackproxy: "owaspzap",
    // CS concepts variants
    objectorientedprogramming: "oop",
    functionalprog: "functionalprogramming",
    fp: "functionalprogramming",
    dsa: "datastructures",
    dataalgorithms: "algorithms",
    sysdesign: "systemdesign",
    "testdrivendevelopment": "tdd",
    "behaviordrivendevelopment": "bdd",
    "domaindrivendesign": "ddd",
    // Methodologies
    agilemethodology: "agile",
    scrummethodology: "scrum",
    safeagile: "safe",
    // Hardware
    rpi: "raspberrypi",
    internetofthings: "iot",
    // Web3
    "ethers.js": "web3",
    "web3.js": "web3",
    cryptocurrency: "blockchain",
    bitcoin: "blockchain",
    // Tooling
    "tailwind": "tailwindcss",
    "react.query": "reactquery",
    tanstackquery: "reactquery",
    "mui": "materialui",
    "shadcn": "shadcnui",
    "shadcn/ui": "shadcnui",
    // CMS / e-com
    wp: "wordpress",
    woo: "woocommerce",
    // Communication
    msteams2: "microsoftteams",
  };
  return ALIASES[stripped] || ALIASES[s] || stripped;
}

function prettyLabel(skill) {
  return String(skill || "").trim();
}

export function getLearnLink(skill) {
  const key = canonicalKey(skill);
  const direct = DIRECT[key];
  if (direct) {
    return { url: direct, label: `Learn ${prettyLabel(skill)}` };
  }
  // Fallback — Google "learn <skill> free tutorial" so users always land on real material.
  return {
    url: `https://www.google.com/search?q=${encodeURIComponent(`learn ${prettyLabel(skill)} free tutorial`)}`,
    label: `Learn ${prettyLabel(skill)}`,
  };
}
